version: '3.8'

services:
  web:
    build: .
    container_name: hostelpulse_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=production-secure-key-9284102
      - PORT=5000
    volumes:
      - ./instance:/app/instance
